repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: trailing-whitespace
    exclude: README.md

- repo: https://github.com/ambv/black
  rev: 21.5b1
  hooks:
  - id: black
    name: Blacken

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    args: [--count, --show-source, --statistics]
