name: CD to dev-dokku

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'materialscloud-org/tools-optimade-client'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install SSH key for dev-dokku
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_DEV_DOKKU }}
        name: id_optimadeclient
        known_hosts: ${{ secrets.SSH_KNOWN_HOST_DEV_DOKKU }}
        config: ${{ secrets.SSH_CONFIG_DEV_DOKKU }}

    - name: Install SSH key for host forwarding
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_JUMP_HOST }}
        name: id_jumphost
        known_hosts: ${{ secrets.SSH_KNOWN_HOST_JUMP_HOST }}
        config: ${{ secrets.SSH_CONFIG_JUMP_HOST }}

    - name: Deploy to dev-dokku
      run: |
        git remote add dokku dokku@materialscloud.io:optimadeclient
        git config --global user.email "casper.w.andersen@sintef.no"
        git config --global user.name "Casper Welzel Andersen"
        git checkout master
        git push dokku master
